spring:
  ##Mysql
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

  ##redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
  jackson:
    parser:
      allow-unquoted-control-chars: true
      allow-unquoted-field-names: true
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 100
  refresh-token-expiration-minutes: 300
  cookie-name: token

mail:
  host: smtp.gmail.com
  port: 587
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

logging:
  level:
    org:
      springframework:
        web: INFO
        security: DEBUG
      hibernate: ERROR

cloud:
  aws:
    credentials:
      access-key: ${ASWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false


oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_SECRET_ID}
    redirect-uri: http://localhost:8080/login/oauth2/code/google
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://openidconnect.googleapis.com/v1/userinfo
    scope: https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile

  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/login/oauth2/code/kakao
    token-uri: https://kauth.kakao.com/oauth/token
    resource-uri: https://kapi.kakao.com/v2/user/me

  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/login/oauth2/code/naver
    token-uri: https://nid.naver.com/oauth2.0/token
    resource-uri: https://openapi.naver.com/v1/nid/me

frontend-uri: http://localhost:3000